Permission.with_deleted.each(&:destroy)

permissions_attributes = [
  { section: 'User', action: 'manage' },
  { section: 'User', action: 'index' },
  { section: 'User', action: 'show' },
  { section: 'User', action: 'create' },
  { section: 'User', action: 'update' },
  { section: 'User', action: 'destroy' },
  { section: 'User', action: 'documents' },
  { section: 'User', action: 'permissions' },
  { section: 'UserType', action: 'manage' },
  { section: 'UserType', action: 'index' },
  { section: 'UserType', action: 'show' },
  { section: 'UserType', action: 'create' },
  { section: 'UserType', action: 'update' },
  { section: 'UserType', action: 'destroy' },
  { section: 'UserType', action: 'users' },
  { section: 'Fleet', action: 'manage' },
  { section: 'Fleet', action: 'index' },
  { section: 'Fleet', action: 'show' },
  { section: 'Fleet', action: 'create' },
  { section: 'Fleet', action: 'update' },
  { section: 'Fleet', action: 'destroy' },
  { section: 'Fleet', action: 'vehicles' },
  { section: 'VehicleType', action: 'manage' },
  { section: 'VehicleType', action: 'index' },
  { section: 'VehicleType', action: 'show' },
  { section: 'VehicleType', action: 'create' },
  { section: 'VehicleType', action: 'update' },
  { section: 'VehicleType', action: 'destroy' },
  { section: 'Vehicle', action: 'manage' },
  { section: 'Vehicle', action: 'index' },
  { section: 'Vehicle', action: 'show' },
  { section: 'Vehicle', action: 'create' },
  { section: 'Vehicle', action: 'update' },
  { section: 'Vehicle', action: 'destroy' },
  { section: 'Vehicle', action: 'fuel_records' },
  { section: 'Vehicle', action: 'kilometer_records' },
  { section: 'Vehicle', action: 'maintenances' },
  { section: 'Vehicle', action: 'failures' },
  { section: 'Vehicle', action: 'documents' },
  { section: 'Vehicle', action: 'images' },
  { section: 'FuelType', action: 'manage' },
  { section: 'FuelType', action: 'index' },
  { section: 'FuelType', action: 'show' },
  { section: 'FuelType', action: 'create' },
  { section: 'FuelType', action: 'update' },
  { section: 'FuelType', action: 'destroy' },
  { section: 'FuelRecord', action: 'manage' },
  { section: 'FuelRecord', action: 'index' },
  { section: 'FuelRecord', action: 'show' },
  { section: 'FuelRecord', action: 'create' },
  { section: 'FuelRecord', action: 'update' },
  { section: 'FuelRecord', action: 'destroy' },
  { section: 'Brand', action: 'manage' },
  { section: 'Brand', action: 'index' },
  { section: 'Brand', action: 'show' },
  { section: 'Brand', action: 'create' },
  { section: 'Brand', action: 'update' },
  { section: 'Brand', action: 'destroy' },
  { section: 'Brand', action: 'models' },
  { section: 'Model', action: 'manage' },
  { section: 'Model', action: 'index' },
  { section: 'Model', action: 'show' },
  { section: 'Model', action: 'create' },
  { section: 'Model', action: 'update' },
  { section: 'Model', action: 'destroy' },
  { section: 'MaintenancePlan', action: 'manage' },
  { section: 'MaintenancePlan', action: 'index' },
  { section: 'MaintenancePlan', action: 'show' },
  { section: 'MaintenancePlan', action: 'create' },
  { section: 'MaintenancePlan', action: 'update' },
  { section: 'MaintenancePlan', action: 'destroy' },
  { section: 'MaintenancePlan', action: 'maintenances' },
  { section: 'MaintenancePlan', action: 'failures' },
  { section: 'Maintenance', action: 'manage' },
  { section: 'Maintenance', action: 'index' },
  { section: 'Maintenance', action: 'show' },
  { section: 'Maintenance', action: 'create' },
  { section: 'Maintenance', action: 'update' },
  { section: 'Maintenance', action: 'destroy' },
  { section: 'Maintenance', action: 'activate' },
  { section: 'Maintenance', action: 'desactivate' },
  { section: 'Maintenance', action: 'spares' },
  { section: 'Maintenance', action: 'add_spare' },
  { section: 'Maintenance', action: 'remove_spare' },
  { section: 'MaintenanceType', action: 'manage' },
  { section: 'MaintenanceType', action: 'index' },
  { section: 'MaintenanceType', action: 'show' },
  { section: 'MaintenanceType', action: 'create' },
  { section: 'MaintenanceType', action: 'update' },
  { section: 'MaintenanceType', action: 'destroy' },
  { section: 'Document', action: 'manage' },
  { section: 'Document', action: 'index' },
  { section: 'Document', action: 'show' },
  { section: 'Document', action: 'create' },
  { section: 'Document', action: 'update' },
  { section: 'Document', action: 'destroy' },
  { section: 'Report', action: 'manage' },
  { section: 'Report', action: 'index' },
  { section: 'Report', action: 'report_types' },
  { section: 'Report', action: 'export_report' },
  { section: 'Warehouse', action: 'manage' },
  { section: 'Warehouse', action: 'index' },
  { section: 'Warehouse', action: 'show' },
  { section: 'Warehouse', action: 'create' },
  { section: 'Warehouse', action: 'update' },
  { section: 'Warehouse', action: 'destroy' },
  { section: 'Debate', action: 'manage' },
  { section: 'Debate', action: 'index' },
  { section: 'Debate', action: 'show' },
  { section: 'Debate', action: 'create' },
  { section: 'Debate', action: 'update' },
  { section: 'Debate', action: 'destroy' },
  { section: 'Failure', action: 'manage' },
  { section: 'Failure', action: 'index' },
  { section: 'Failure', action: 'show' },
  { section: 'Failure', action: 'create' },
  { section: 'Failure', action: 'update' },
  { section: 'Failure', action: 'destroy' },
  { section: 'Failure', action: 'images' },
  { section: 'Failure', action: 'documents' },
  { section: 'GasStation', action: 'manage' },
  { section: 'GasStation', action: 'index' },
  { section: 'GasStation', action: 'show' },
  { section: 'GasStation', action: 'create' },
  { section: 'GasStation', action: 'update' },
  { section: 'GasStation', action: 'destroy' },
  { section: 'Image', action: 'manage' },
  { section: 'Image', action: 'index' },
  { section: 'Image', action: 'show' },
  { section: 'Image', action: 'create' },
  { section: 'Image', action: 'update' },
  { section: 'Image', action: 'destroy' },
  { section: 'KilometerRecord', action: 'manage' },
  { section: 'KilometerRecord', action: 'index' },
  { section: 'KilometerRecord', action: 'show' },
  { section: 'KilometerRecord', action: 'create' },
  { section: 'KilometerRecord', action: 'update' },
  { section: 'KilometerRecord', action: 'destroy' },
  { section: 'NotificationType', action: 'manage' },
  { section: 'NotificationType', action: 'index' },
  { section: 'NotificationType', action: 'show' },
  { section: 'NotificationType', action: 'create' },
  { section: 'NotificationType', action: 'update' },
  { section: 'NotificationType', action: 'destroy' },
  { section: 'Notification', action: 'manage' },
  { section: 'Notification', action: 'index' },
  { section: 'Notification', action: 'show' },
  { section: 'Notification', action: 'update' },
  { section: 'EnableNotificationType', action: 'manage' },
  { section: 'EnableNotificationType', action: 'index' },
  { section: 'EnableNotificationType', action: 'create' },
  { section: 'EnableNotificationType', action: 'destroy' },
  { section: 'Permission', action: 'manage' },
  { section: 'Permission', action: 'index' },
  { section: 'Permission', action: 'show' },
  { section: 'Permission', action: 'create' },
  { section: 'Permission', action: 'update' },
  { section: 'Permission', action: 'destroy' },
  { section: 'UserType', action: 'manage' },
  { section: 'UserType', action: 'index' },
  { section: 'UserType', action: 'show' },
  { section: 'UserType', action: 'create' },
  { section: 'UserType', action: 'update' },
  { section: 'UserType', action: 'destroy' },
  { section: 'UserType', action: 'add_permission' },
  { section: 'UserType', action: 'remove_permission' },
  { section: 'Response', action: 'manage' },
  { section: 'Response', action: 'index' },
  { section: 'Response', action: 'show' },
  { section: 'Response', action: 'create' },
  { section: 'Response', action: 'update' },
  { section: 'Response', action: 'destroy' },
  { section: 'Unit', action: 'manage' },
  { section: 'Unit', action: 'index' },
  { section: 'Unit', action: 'show' },
  { section: 'Unit', action: 'create' },
  { section: 'Unit', action: 'update' },
  { section: 'Unit', action: 'destroy' },
  { section: 'UnitType', action: 'manage' },
  { section: 'UnitType', action: 'index' },
  { section: 'UnitType', action: 'show' },
  { section: 'UnitType', action: 'create' },
  { section: 'UnitType', action: 'update' },
  { section: 'UnitType', action: 'destroy' },
  { section: 'UnitType', action: 'units' },
]

permissions_attributes.each { |attributes| Permission.find_or_create_by attributes }

# Permisos esenciales para todos los tipos de usuarios
lista_permisos = Permission.find_or_create_by section: 'Permission', action: 'index'
ver_permiso = Permission.find_or_create_by section: 'Permission', action: 'show'
serv_user_permiso = Permission.find_or_create_by section: 'User', action: 'permissions'
ver_usuario = Permission.find_or_create_by section: 'User', action: 'show'
manage_debate = Permission.find_or_create_by section: 'Debate', action: 'manage'
manage_response = Permission.find_or_create_by section: 'Response', action: 'manage'

UserType.where.not(name: 'admin').each do |user_type|
  UserTypePermission.find_or_create_by user_type_id: user_type.id, permission_id: lista_permisos.id
  UserTypePermission.find_or_create_by user_type_id: user_type.id, permission_id: ver_permiso.id
  UserTypePermission.find_or_create_by user_type_id: user_type.id, permission_id: serv_user_permiso.id
  UserTypePermission.find_or_create_by user_type_id: user_type.id, permission_id: ver_usuario.id
  UserTypePermission.find_or_create_by user_type_id: user_type.id, permission_id: ver_usuario.id
  UserTypePermission.find_or_create_by user_type_id: user_type.id, permission_id: manage_debate.id
  UserTypePermission.find_or_create_by user_type_id: user_type.id, permission_id: manage_response.id
end